name: gcib_bank
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auth_repo:
    path: packages/auth_repo
  cached_network_image: ^3.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  data_api:
    path: packages/data_api
  data_storage:
    path: packages/data_storage
  invst_repo:
    path: packages/invst_repo
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.19.0

dev_dependencies:
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
