name: data_storage
description: This is where all the API request are made and storage of data

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dev_dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2
  data_api:
    path: "../data_api"
